### ISSUE TITLE
I need help the song of wars launcher da giving me problem not entering

### ISSUE THREAD

**Issue by mestredanielyt** [Songs-of-War/Songs-of-War-Launcher#102]
```
TypeError: result.toFixed is not a function
    at Object.dataValue (C:\Users\ALVARO\AppData\Local\Programs\songs-of-war-launcher\resources\app.asar\node_modules\wmic-sys-info\lib\helpers.js:31:17)
    at C:\Users\ALVARO\AppData\Local\Programs\songs-of-war-launcher\resources\app.asar\node_modules\wmic-sys-info\index.js:75:29
    at ChildProcess.exithandler (child_process.js:308:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

---

Songs of War Game 1.10.12
Electron 12.0.7
win32 10.0.19042
Locale: pt-BR

**Comment by eDexiam** [comment]
Duplicated of #89
