### ISSUE TITLE
Launcher not loading kubuntu

### ISSUE THREAD

**Issue by ByteZ9X** [Songs-of-War/Songs-of-War-Launcher#140]
```
TypeError: Cannot read property 'getServer' of null
    at refreshServerStatus (file:///tmp/.mount_Songs-ComHDV/resources/app.asar/app/assets/js/scripts/landing.js:284:49)
    at file:///tmp/.mount_Songs-ComHDV/resources/app.asar/app/assets/js/scripts/landing.js:372:46
```

---

Songs of War Game 1.10.14
Electron 12.1.0
linux 5.11.0-37-generic
Locale: en-US

**Comment by eDexiam** [comment]
The underlying code that displayed this error is gone so this should no longer be an issue
