### ISSUE TITLE
Bug while opening the launcher

### ISSUE THREAD

**Issue by ZhaleTheDoggo** [Songs-of-War/Songs-of-War-Launcher#147]
Okay, so. For some reason, every time I open the launcher, it loads for a while and then gives an error message and won’t let you play. Apparently, this bug is for everyone. Not sure if it’s the same error, but at least no one can open the launcher and access to the server
The following error message is given every time:
 
Unhandled Promise Rejection
RequestError: certificate has expired
    at ClientRequest.<anonymous> (C:/Users/*user*/AppData/Local/Programs/Songs-of-War-Launcher/resources/app.asar/node_modules/got/dist/source/core/index.js:956:111)
    at ClientRequest.origin.emit (C:/Users/*user*/AppData/Local/Programs/Songs-of-War-Launcher/resources/app.asar/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)

**To Reproduce**
1. Open the launcher
2. Wait for a while
3. It should give you an error

 - OS: Windows
 - Launcher version: 1.10.5 (official, not alpha, but it’s the same problem with both)

**Comment by AlisterVangelis** [comment]
I had the same problem:

Unhandled Promise Rejection
RequestError: certificate has expired
    at ClientRequest.<anonymous> (C:/Users/User/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/node_modules/got/dist/source/core/index.js:956:111)
    at ClientRequest.origin.emit (C:/Users/User/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)

**Comment by eDexiam** [comment]
Fixed in v1.10.15
