### ISSUE TITLE
Launcher not opening bug

### ISSUE THREAD

**Issue by liorad** [Songs-of-War/Songs-of-War-Launcher#148]
```
TypeError: Cannot read property 'getServer' of null
    at refreshServerStatus (file:///C:/Users/rache/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/landing.js:255:49)
    at file:///C:/Users/rache/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/landing.js:343:46
```

---

Songs of War Game 2.0.0-alpha2
Electron 13.3.0
win32 10.0.19042
Locale: he

**Comment by eDexiam** [comment]
Duplicate of #140
