### ISSUE TITLE
Handle Microsoft logins

### ISSUE THREAD

**Issue by lucasboss45** [Songs-of-War/Songs-of-War-Launcher#71]
Implement
https://wiki.vg/Microsoft_Authentication_Scheme#Microsoft_OAuth_Flow

**Comment by eDexiam** [comment]
Very early (and buggy) version implemented with #105, this is far from being stable enough to even have an alpha version

**Comment by liorad** [comment]
maybe you could temporarily make the server open for normal launcher so player would be able to migrate their account so it wont be a risk to not upgrading the account to late and when you finish making a log in for Microsoft account

**Comment by eDexiam** [comment]
Commit d4dbc7e is somewhat stable, so, an alpha release will be made, all issues regarding Microsoft should be reported here.

**Comment by jamesljlster** [comment]
Hello Dexiam,

I can log in with 2FA enabled Microsoft account, but failed to start the game after clicking 'play'.
Here is the log: [-1630928929093.log](https://github.com/Songs-of-War/Songs-of-War-Launcher/files/7115747/-1630928929093.log)

**Comment by jamesljlster** [comment]
> Hello Dexiam,
> 
> I can log in with 2FA enabled Microsoft account, but failed to start the game after clicking 'play'.
> Here is the log: [-1630928929093.log](https://github.com/Songs-of-War/Songs-of-War-Launcher/files/7115747/-1630928929093.log)

Hello Dexiam,

After revert some changes from <https://github.com/dscalzi/HeliosLauncher/commit/0346597afeddd45f1b28885c3dd9ae24412e8ff8>, I can now start the game successfully:

```diff
diff --git a/app/assets/js/configmanager.js b/app/assets/js/configmanager.js
index 8be0e78..26a4fe3 100644
--- a/app/assets/js/configmanager.js
+++ b/app/assets/js/configmanager.js
@@ -2,8 +2,6 @@ const fs   = require('fs-extra')
 const os   = require('os')
 const path = require('path')
 
-const logger = require('./loggerutil')('%c[ConfigManager]', 'color: #a02d2a; font-weight: bold')
-
 const sysRoot = process.env.APPDATA || (process.platform == 'darwin' ? process.env.HOME + '/Library/Application Support' : process.env.HOME)
 // TODO change
 const dataPath = path.join(sysRoot, '.songsofwar')
@@ -165,9 +163,9 @@ exports.load = function(){
             config = JSON.parse(fs.readFileSync(configPath, 'UTF-8'))
             doValidate = true
         } catch (err){
-            logger.error(err)
-            logger.log('Configuration file contains malformed JSON or is corrupt.')
-            logger.log('Generating a new configuration file.')
+            console.error(err)
+            console.log('Configuration file contains malformed JSON or is corrupt.')
+            console.log('Generating a new configuration file.')
             fs.ensureDirSync(path.join(configPath, '..'))
             config = DEFAULT_CONFIG
             exports.save()
@@ -177,7 +175,7 @@ exports.load = function(){
             exports.save()
         }
     }
-    logger.log('Successfully Loaded')
+    console.log('Successfully Loaded')
 }
 
 /**
@@ -841,4 +839,4 @@ exports.getCompabilityCheckDisabled = function () {
  */
 exports.setCompabilityCheckDisabled = function (isDisabled) {
     config.special.compatibility.disableCheck = isDisabled
-}
\ No newline at end of file
+}
```

(oof the new line...)

It seems that there is a circular dependency in <https://github.com/Songs-of-War/Songs-of-War-Launcher/blob/new-ms-auth/app/assets/js/configmanager.js#L5> and <https://github.com/Songs-of-War/Songs-of-War-Launcher/blob/new-ms-auth/app/assets/js/loggerutil.js#L2>.  
Since I'm not a JS engineer, don't know if the fix is correct or not.  
So just report what I have tried here.

**Comment by eDexiam** [comment]
> > Hello Dexiam,
> > I can log in with 2FA enabled Microsoft account, but failed to start the game after clicking 'play'.
> > Here is the log: [-1630928929093.log](https://github.com/Songs-of-War/Songs-of-War-Launcher/files/7115747/-1630928929093.log)
> 
> Hello Dexiam,
> 
> After reverting some changes from [dscalzi@0346597](https://github.com/dscalzi/HeliosLauncher/commit/0346597afeddd45f1b28885c3dd9ae24412e8ff8), I can now start the game successfully:
> 
> ```diff
> diff --git a/app/assets/js/configmanager.js b/app/assets/js/configmanager.js
> index 8be0e78..26a4fe3 100644
> --- a/app/assets/js/configmanager.js
> +++ b/app/assets/js/configmanager.js
> @@ -2,8 +2,6 @@ const fs   = require('fs-extra')
>  const os   = require('os')
>  const path = require('path')
>  
> -const logger = require('./loggerutil')('%c[ConfigManager]', 'color: #a02d2a; font-weight: bold')
> -
>  const sysRoot = process.env.APPDATA || (process.platform == 'darwin' ? process.env.HOME + '/Library/Application Support' : process.env.HOME)
>  // TODO change
>  const dataPath = path.join(sysRoot, '.songsofwar')
> @@ -165,9 +163,9 @@ exports.load = function(){
>              config = JSON.parse(fs.readFileSync(configPath, 'UTF-8'))
>              doValidate = true
>          } catch (err){
> -            logger.error(err)
> -            logger.log('Configuration file contains malformed JSON or is corrupt.')
> -            logger.log('Generating a new configuration file.')
> +            console.error(err)
> +            console.log('Configuration file contains malformed JSON or is corrupt.')
> +            console.log('Generating a new configuration file.')
>              fs.ensureDirSync(path.join(configPath, '..'))
>              config = DEFAULT_CONFIG
>              exports.save()
> @@ -177,7 +175,7 @@ exports.load = function(){
>              exports.save()
>          }
>      }
> -    logger.log('Successfully Loaded')
> +    console.log('Successfully Loaded')
>  }
>  
>  /**
> @@ -841,4 +839,4 @@ exports.getCompabilityCheckDisabled = function () {
>   */
>  exports.setCompabilityCheckDisabled = function (isDisabled) {
>      config.special.compatibility.disableCheck = isDisabled
> -}
> \ No newline at end of file
> +}
> ```
> 
> (oof the new line...)
> 
> It seems that there is a circular dependency in https://github.com/Songs-of-War/Songs-of-War-Launcher/blob/new-ms-auth/app/assets/js/configmanager.js#L5 and https://github.com/Songs-of-War/Songs-of-War-Launcher/blob/new-ms-auth/app/assets/js/loggerutil.js#L2.
> Since I'm not a JS engineer, don't know if the fix is correct or not.
> So just report what I have tried here.

Hey, thanks for your insight I'm currently looking for the exact cause right now.
PS: I wouldn't classify as a "JS engineer" either :p

**Comment by liorad** [comment]
i dont know if it is becusae of the migrated account but everytime i try to log in it says disconnected and i need to spam the join button antill it will let me in
![image](https://user-images.githubusercontent.com/68856529/133608790-5d8b0121-cf86-4f40-8c5a-ef410807dbdf.png)

**Comment by jamesljlster** [comment]
> I don't know if it is because of the migrated account but every time I try to log in it says disconnected and I need to spam the join button until it will let me in
> ![image](https://user-images.githubusercontent.com/68856529/133608790-5d8b0121-cf86-4f40-8c5a-ef410807dbdf.png)

The problem happens to me as well.
Once it let me in, it would let me in unless I restart the game.
I have seen some discussion from others about this problem on Discord.
Maybe the problem is on the server side instead of launcher side, but still not sure.

**Comment by eDexiam** [comment]
> The problem happens to me as well.
> Once it let me in, it would let me in unless I restart the game.
> I have seen some discussion from others about this problem on Discord.
> Maybe the problem is on the server side instead of launcher side, but still not sure.

Yes this is server-side, from my experience it's the bungeecord proxy throttling your connection, although it doesn't display a specific message that says so unlike spigot.

**Comment by eDexiam** [comment]
Microsoft login seems to be working properly for users of only one account, however I haven't received a lot of feedback about multi account support.
If you have multiple Minecraft accounts and are able to test the feature please let me know I'd appreciate it.

**Comment by SmickyAkendor** [comment]
Hey i have download this version but he say : Response Code 401 Unauthorized !
I have migrated my account Mojang ---> Microsoft in my second account microsoft ; i click Login with Microsoft and i enter my informations : i click and i receive this messages !
If someone help me , please !? 
Thanks you !

**Comment by SmickyAkendor** [comment]
Where do I find the complete launcher log?

**Comment by SmickyAkendor** [comment]
I saw on BlueMap that on the village where I was a citizen, I am no longer registered nor on any other towns or villages.
Maybe I accidentally closed the SOW account without doing it on purpose? I do not know ...

**Comment by AlanLime** [comment]
I have the same issue with Response Code 401, here's the launcher log:
![error401bulshit](https://user-images.githubusercontent.com/92811072/137950663-0dff313c-f2df-4a28-8465-d1d250fdcab0.PNG)
hope this could help in solving the issue

**Comment by eDexiam** [comment]
> I have the same issue with Response Code 401, here's the launcher log: ![error401bulshit](https://user-images.githubusercontent.com/92811072/137950663-0dff313c-f2df-4a28-8465-d1d250fdcab0.PNG) hope this could help in solving the issue

Please try the version below and let me know if anything changes
https://github.com/Songs-of-War/Songs-of-War-Launcher/suites/4262810499/artifacts/110775154

**Comment by AlanLime** [comment]
Yeah it works now, thanks

**Comment by Damascusari** [comment]
Here are the issues I found so far with multiple accounts:
Any login: 
- With 2fa, only code sent by email authentication works. Neither text message nor authenticator app work.

Second account login:
- Sometimes fails, no observed pattern.

Third account login: three accounts don't work at all. I need to log out of at least one account of the two to log into a third.

Logout:
- Always errors out with this error, which appears twice:
Unhandled Promise Rejection
TypeError: Cannot read property 'type' of undefined
    at Object.exports.removeAccount (C:/Users/Invy/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/authmanager.js:110:17)
    at processLogOut (file:///C:/Users/Invy/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/settings.js:453:17)
    at EventEmitter.<anonymous> (file:///C:/Users/Invy/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/settings.js:469:5)
    at Object.onMessage (electron/js2c/renderer_init.js:93:1117)

Cancelling login causes launcher to load endlessly

**Comment by eDexiam** [comment]
> Here are the issues I found so far with multiple accounts: Any login:
> 
> * With 2fa, only code sent by email works. Neither text message nor authenticator app work.
I don't think that's launcher bound

> Second account login:
> 
> * Sometimes fails, no observed pattern.
> 
> Third account login: three accounts don't work at all. I need to log out of at least one account of the two to log into a third.
> 
> Logout:
> 
> * Always errors out with this error, which appears twice:
>   Unhandled Promise Rejection
>   TypeError: Cannot read property 'type' of undefined
>   at Object.exports.removeAccount (C:/Users/Invy/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/authmanager.js:110:17)
>   at processLogOut (file:///C:/Users/Invy/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/settings.js:453:17)
>   at EventEmitter. (file:///C:/Users/Invy/AppData/Local/Programs/songs-of-war-launcher/resources/app.asar/app/assets/js/scripts/settings.js:469:5)
>   at Object.onMessage (electron/js2c/renderer_init.js:93:1117)
> 
> Cancelling login causes launcher to load endlessly

Could you provide the launcher log whenever any of these issues occur?
