### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Pythonesc** [Songs-of-War/Songs-of-War-Launcher#86]
```
TypeError: result.toFixed is not a function
    at Object.dataValue (C:\Users\[name]\AppData\Local\Programs\Songs-of-War-Launcher\Songs of War Launcher\resources\app.asar\node_modules\wmic-sys-info\lib\helpers.js:31:17)
    at C:\Users\[name]\AppData\Local\Programs\Songs-of-War-Launcher\Songs of War Launcher\resources\app.asar\node_modules\wmic-sys-info\index.js:75:29
    at ChildProcess.exithandler (child_process.js:303:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

---

Songs of War Game 1.10.5
Electron 11.2.3
win32 10.0.19041
Locale: en-GB

**Comment by eDexiam** [comment]
Duplicate #89
