### ISSUE TITLE
Launcher didn't complete launching.

### ISSUE THREAD

**Issue by Kyberoff** [Songs-of-War/Songs-of-War-Launcher#95]
```
TypeError: result.toFixed is not a function
    at Object.dataValue (C:\Users\"Name"\AppData\Local\Programs\songs-of-war-launcher\resources\app.asar\node_modules\wmic-sys-info\lib\helpers.js:31:17)
    at C:\Users\"Name"\AppData\Local\Programs\songs-of-war-launcher\resources\app.asar\node_modules\wmic-sys-info\index.js:75:29
    at ChildProcess.exithandler (child_process.js:308:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

---

Songs of War Game 1.10.12
Electron 12.0.7
win32 10.0.19042
Locale: en-US

**Comment by eDexiam** [comment]
When does this happen exactly?

**Comment by eDexiam** [comment]
Duplicated #89

**Comment by Kyberoff** [comment]
It happened whenever I tried to launch the Launcher. It was right after I updated it 2 days ago. It says installed and all that, then it goes to an error screen.
